### ISSUE TITLE
Where are results?

### ISSUE THREAD

**Issue by wanggis** [kasungayan/LSTMMSNet#2]
Hello , Kasun.
Your paper and idea are amazing. I'm interested at your program and  want to reproduce your framework.But I couldn't find your paper's results in the repositories. All of them is empty. Could you upload your results or send me your results via email.
My e-mail address is ws260308526519@163.com.
Thanks!

**Comment by kasungayan** [comment]
Hi @wanggis,

Thanks for your interest in our work. The results can be found in our paper: https://arxiv.org/pdf/1909.04293.pdf

Regards,
Kasun
